meta_product_name: "STATIONNÉLO"
meta_title: "Stationnélo - Gare ton vélo en Île-de-France"
meta_description: "Stationnélo te permet de localiser les parkings à vélos en Île-de-France et de t'y rendre."
meta_image: "stationnelo.png" # should exist in `app/assets/images/`
